### ISSUE TITLE
Better component architecture arrangement

### ISSUE THREAD

**Issue by AndrianinaH** [julkwel/signaleo#10]
Mila restructurena le appli, tokony misy sepération entre layout d'un utilisateur tsy connecté sy utilisateur connecté, 
-mba elana amle mi render anle fil d'actu nefa tsy mbola authentifier le utilisateur
-mba atsara kokoa ny design fa tsy misy BottomTabBar nefa tsy authentifier

**Comment by julkwel** [comment]
#6

**Comment by julkwel** [comment]
#Develop
