### ISSUE TITLE
Ajout option dans "Inona no mitranga?

### ISSUE THREAD

**Issue by rzohasi** [julkwel/signaleo#28]
Rehefa mba hoe "Signaleo" ihany ny contexte dia mangataka ny anampiana option iray hoe "Fanendehana" ao amin'ilay liste déroulante "Inona no mitranga?"
Mety hanampy olona maro amin'ny resaka fitandremana eny amin'ny fifamoivoizana eny ny fahalalany an'ireo infos ireo

**Comment by julkwel** [comment]
Fix #2ae2ac3
